### ISSUE TITLE
获取id失败

### ISSUE THREAD

**Issue by LDH0218** [cryptoli/MergeCFXs#1]
![photo_2024-01-22_11-44-29](https://github.com/cryptoli/MergeCFXs/assets/104433685/3d75c0f1-a2cf-451a-9abf-a69fc859f80a)
为啥会这样

**Comment by cryptoli** [comment]
请检查你的网络是否有问题，这个报错是从cfxs.world读取你拥有的id报错的，如果你本地连接cfxs.world没问题，请重试。

**Comment by LDH0218** [comment]
> 请检查你的网络是否有问题，这个报错是从cfxs.world读取你拥有的id报错的，如果你本地连接cfxs.world没问题，请重试。

还是不行，现在好像没办法访问了

**Comment by cryptoli** [comment]
![image](https://github.com/cryptoli/MergeCFXs/assets/97449000/8d93bf7f-27e7-4c74-b900-643c2fb16450)
我刚试了还可以，你可以找一台vps试试

**Comment by LDH0218** [comment]
好的
